### ISSUE TITLE
Wiki-like behavior

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#112]
(per conversations with @arademaker)

One way to improve the throughput of the efforts being made is to adopt a more agile process where submissions are (mostly) automatically approved and, if later they are decided to be subpar, can be then removed.  In other words, adopt a wikipedia-style way of processing suggestions.

In terms of the current system, very little would change, since we would like to still keep track of the evolution of each entry: regularly (to be decided -- maybe daily?) a process will automatically COMMIT all suggestions with at least ONE vote.

If a suggestion that was accepted is questioned by someone else, that person can submit a new suggestion to act upon it (either by removing a newly added word, or adding a newly removed word, for example).

New batch submissions from automatic processes will be inserted into the system with no automatic votes unless we can ascertain the quality of the batch beforehand.

We may want to change the system so that submissions by people outside a trusted group don't get an automatic vote to avoid spam / abuse.

**Comment by vcvpaiva** [comment]
hmm, not totally clear to me that this is a good idea.
Improving the process is certainly necessary and maybe this is the way
forward.
but surely one could try to simply implement the automatic commit with two
votes, instead of one, first.
if this works well, we might push forward and change to one vote only
commit, or not.
erring on the side of caution would seem to me a good idea.

**Comment by fcbr** [comment]
Looks like we are not going wiki-style.  Closing this for now.
