### ISSUE TITLE
add link to node in allegro from synset page

### ISSUE THREAD

**Issue by odanoburu** [fcbr/cl-wnbrowser#198]
it would be nice to have the allegro page for a synset one click away. e.g., have a link to http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/node/%3Chttps://w3id.org/own-pt/wn30-pt/instances/synset-02765692-v%3E from http://wn.mybluemix.net/synset?id=02765692-v

**Comment by arademaker** [comment]
We must have the urls of the synsets dereferenced:

https://www.w3.org/DesignIssues/LinkedData.html

**Comment by arademaker** [comment]
We do have already a stable URL schema for OWN-PT. For the example above

https://w3id.org/own-pt/wn30-pt/instances/synset-02765692-v

@hmuniz do you think it is easy to implement this extra link in the synset page to the URL above? This URL redirects to the Allegro Graph page. In the future, if we change the triplestore or move it for another server, we just need to change w3id (https://w3id.org). 

I believe this issue is too simple that would be nice to close it soon.

**Comment by hmuniz** [comment]
For sure, It's simple. I will close it soon.

**Comment by hmuniz** [comment]
Done.

**Comment by arademaker** [comment]
Sorry, maybe better to link to the EN version

https://w3id.org/own-pt/wn30-en/instances/synset-02765692-v

**Comment by hmuniz** [comment]
Ok

**Comment by hmuniz** [comment]
It's done.
