### ISSUE TITLE
allow search in gloss en and pt

### ISSUE THREAD

**Issue by arademaker** [fcbr/cl-wnbrowser#70]
criar 2 novos índices e também nas sugestões. Precisamos poder pesquisar por palavras que terminem com um dado padrão (regex).

**Comment by vcvpaiva** [comment]
Acho que o nome desse issue esta' errado ou "misleading". No momento o sistema faz busca nas glosas. o que eu queria 'e o contrario poder parar de procurar nas glosas, pois qdo a palavra que estou procurando aparece como explicacao de outra, as coisas as vezes ficam confusas. um exemplo o verbo "punish" e' relativamente raro e erudito, eu esperaria um unico synset e na verdade 'e so' um mesmo, mas temos 7 na interface.

**Comment by arademaker** [comment]
Não valeria, o que queremos é poder restringir a busca nos campos de glosas assim como podemos restringir para os campos word.

Agora a interface parece não estar funcionando para nenhum campo, mas deveriamos poder pesquisar por: 1)  "punish"; 2) "word_en:punish"; e 3) "gloss_en:punish". 

No caso 1, busca em todos os índices (campos), no caso 2 apenas nos campos word_en e no caso 3 apenas no campo gloss_en.

Além disso, o issue trata também de permitir busca nas sugestões.

**Comment by vcvpaiva** [comment]
ok, o que eu quero e'  o #2, mas se tiver as tres possibilidades 'e muito
bom.

2015-04-27 10:13 GMT-07:00 Alexandre Rademaker notifications@github.com:

> Não valeria, o que queremos é poder restringir a busca nos campos de
> glosas assim como podemos restringir para os campos word.
> 
> Agora a interface parece não estar funcionando para nenhum campo, mas
> deveriamos poder pesquisar por: 1) "punish"; 2) "word_en:punish"; e 3)
> "gloss_en:punish".
> 
> No caso 1, busca em todos os índices (campos), no caso 2 apenas nos campos
> word_en e no caso 3 apenas no campo gloss_en.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/70#issuecomment-96743987.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
adicionei indices para gloss_en, gloss_pt, example_t.

para um melhor controle, peco que por favor abram issues especificos para os outros enhancements pedidos

**Comment by vcvpaiva** [comment]
Fabricio,
que setting eu preciso usar pra ver pra "punish" somente o synset
1. 02499629-v http://logics.emap.fgv.br/wn/synset?id=02499629-v
   penalise, punish, penalize \* | penalizar, punir, castigar *
   - _impose a penalty on; inflict punishment on; "The students were
     penalized for showing up late for class"; "we had to punish the dog for
     soiling the floor again"_

em vez dos 7 que eu vejo qdo peco "verbo"?? eu vejo todos os que tem
"punish" na definicao, na glosa, ou no examplo. isto e':
1. 02500775-v http://logics.emap.fgv.br/wn/synset?id=02500775-v
   scourge
   - _punish severely; excoriate_
2. 02500265-v http://logics.emap.fgv.br/wn/synset?id=02500265-v amerce
   - _punish with an arbitrary penalty_
3. 02500619-v http://logics.emap.fgv.br/wn/synset?id=02500619-v
   victimize, victimise \* | vitimar *
   - _punish unjustly_
4. 02483828-v http://logics.emap.fgv.br/wn/synset?id=02483828-v
   pillory
   - _punish by putting in a pillory_
5. 02498987-v http://logics.emap.fgv.br/wn/synset?id=02498987-v amerce
   - _punish by a fine imposed arbitrarily by the discretion of the
     court_
6. 02499629-v http://logics.emap.fgv.br/wn/synset?id=02499629-v
   penalise, punish, penalize \* | penalizar, punir, castigar *
   - _impose a penalty on; inflict punishment on; "The students were
     penalized for showing up late for class"; "we had to punish the dog for
     soiling the floor again"_
7. 02553428-v http://logics.emap.fgv.br/wn/synset?id=02553428-v
   correct, discipline, sort_out
   - _punish in order to gain control or enforce obedience; "The teacher
     disciplined the pupils rather frequently"_

obrigada,
Valeria

2015-04-27 12:31 GMT-07:00 Fabricio Rosario notifications@github.com:

> adicionei indices para gloss_en, gloss_pt, example_t.
> 
> para um melhor controle, peco que por favor abram issues especificos para
> os outros enhancements pedidos
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/70#issuecomment-96789406.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by fcbr** [comment]
Se eu entendi bem, o que voce quer e' "word_en:<palavra>", e.g.:

http://logics.emap.fgv.br/wn/search?term=word_en%3Apunish

**Comment by vcvpaiva** [comment]
Sim 'e isso mesmo, it's just not obvious that the usage should be
word_en WORD.
thanks!

On Mon, Apr 27, 2015 at 1:26 PM, Fabricio Rosario notifications@github.com
wrote:

> Se eu entendi bem, o que voce quer e' "word_en:<palavra>", e.g.:
> 
> http://logics.emap.fgv.br/wn/search?term=word_en%3Apunish
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fcbr/cl-wnbrowser/issues/70#issuecomment-96807077.

## 

Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/
